# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

os:
  - linux

dist: focal
r:
  - oldrel
  - release
  - devel
  
r_packages:
  - remotes
  - Hmisc
  - rms
  - covr

addons:
  apt:
    packages:
      - libgit2-dev

# warnings are  errors
warnings_are_errors: true


after_success:
  - Rscript -e 'library(covr); codecov()'
